### ISSUE TITLE
Add to libraries wiki

### ISSUE THREAD

**Issue by francisdb** [dariooddenino/unison-nonempty#1]
you might want to add your library here
https://github.com/unisonweb/unison/wiki/Unison-libraries

**Comment by dariooddenino** [comment]
It's a very trivial library made mostly to see how the process works. I'm not entirely sure it's worth to be added there :smile:

**Comment by francisdb** [comment]
I would like to see that list grow :-)

**Comment by dariooddenino** [comment]
Done!
